platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks!

target 'FenigeSDKExample' do

  pod 'FenigeSDK'

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end